#!/usr/bin/env python3
"""Monthly device catalog sync.

Primary sources:
  iOS  — AppleDB device JSON (identifier, marketing name, type, SoC)
  AOS  — androidtrackers certified-android-devices by_model.json
         (UTF-8 JSON of Google Play's official supported-devices list)

Fallbacks:
  iOS  — DeviceKit Device.generated.swift
  AOS  — Google Play supported_devices.csv (UTF-16)

Existing rows keep their curated camera_position_portrait. Marketing names are
refreshed from the primary source. New rows get an inferred camera position.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import gzip
import io
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
SCHEMA_PATH = os.path.join(ROOT, "schema.sql")

APPLEDB_DEVICES_URL = "https://api.appledb.dev/device/main.json.gz"
ANDROIDTRACKERS_BY_MODEL_URL = (
    "https://raw.githubusercontent.com/androidtrackers/certified-android-devices/"
    "master/by_model.json"
)
DEVICEKIT_URL = (
    "https://raw.githubusercontent.com/devicekit/DeviceKit/"
    "master/Source/Device.generated.swift"
)
PLAY_DEVICES_URL = "https://storage.googleapis.com/play_public/supported_devices.csv"

USER_AGENT = "MobileCameraPlacementDB/1.0 (+https://github.com/amkorousagi/MobileCameraPlacementDB)"

INSERT_ROW_RE = re.compile(
    r"\(\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'"
    r"\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*\)"
)

DEVICEKIT_MAP_RE = re.compile(
    r'case\s+((?:"iPad[^"]+"\s*,\s*)*"iPad[^"]+")\s*:\s*return\s+(\w+)'
)
DEVICEKIT_NAME_RE = re.compile(
    r"Device is an \[([^\]]+)\][^\n]*\n(?:[^\n]*\n)*?\s*case (\w+)",
    re.MULTILINE,
)
IDENTIFIER_RE = re.compile(r'"(iPad[^"]+)"')
IPAD_HW_ID_RE = re.compile(r"^iPad\d+,\d+$")

# DeviceKit enum case -> portrait camera edge (fallback parser only).
KNOWN_IPAD_FAMILY_POSITION = {
    "iPad10": "RIGHT",
    "iPadA16": "RIGHT",
    "iPadAir11M2": "RIGHT",
    "iPadAir13M2": "RIGHT",
    "iPadAir11M3": "RIGHT",
    "iPadAir13M3": "RIGHT",
    "iPadAir11M4": "RIGHT",
    "iPadAir13M4": "RIGHT",
    "iPadPro11M4": "RIGHT",
    "iPadPro13M4": "RIGHT",
    "iPadPro11M5": "RIGHT",
    "iPadPro13M5": "RIGHT",
}

SAMSUNG_LANDSCAPE_NAME_RE = re.compile(
    r"galaxy tab s(?:7|8|9|1[0-9])(?:\+| ultra| fe(?:\+)?| lite)?(?:\s|$)",
    re.IGNORECASE,
)
SAMSUNG_MODEL_RE = re.compile(r"^SM-[TX][0-9]{3}[A-Z0-9]*$", re.IGNORECASE)

SCHEMA_HEADER = """\
-- Mobile Camera Placement DB
-- Language-agnostic hardware mapping of tablet front-camera location
-- in portrait orientation: RIGHT | TOP | LEFT.
--
-- iOS identifiers and names come from AppleDB:
--   https://appledb.dev  /  https://github.com/littlebyteorg/appledb
-- Android model codes (Build.MODEL) and names come from Google Play's
-- certified-device list, via androidtrackers UTF-8 JSON:
--   https://github.com/androidtrackers/certified-android-devices
--
-- camera_position_portrait:
--   RIGHT  camera is on the long edge (right side in portrait; top in landscape)
--   TOP    camera is on the short edge (classic portrait placement)
--   LEFT   reserved for devices with the camera on the opposite long edge
--
-- updated_at is stored as a stable ISO-8601 UTC timestamp so rebuilds are
-- deterministic. Monthly sync bumps it only when a row is added or changed.
-- This file is regenerated by sync_sources.py; curated positions are preserved.

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    model_id TEXT UNIQUE NOT NULL,
    market_name TEXT NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('iOS', 'Android')),
    camera_position_portrait TEXT NOT NULL CHECK (camera_position_portrait IN ('RIGHT', 'TOP', 'LEFT')),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )


def fetch_bytes(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def maybe_decompress(payload: bytes) -> bytes:
    if payload.startswith(b"\x1f\x8b"):
        return gzip.decompress(payload)
    return payload


def fetch_text(url: str, encoding: str = "utf-8") -> str:
    return maybe_decompress(fetch_bytes(url)).decode(encoding)


def fetch_json(url: str):
    payload = maybe_decompress(fetch_bytes(url))
    return json.loads(payload.decode("utf-8"))


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def model_sort_key(model_id: str) -> tuple:
    parts = re.findall(r"[A-Za-z]+|\d+", model_id)
    key = []
    for part in parts:
        key.append((1, int(part)) if part.isdigit() else (0, part.upper()))
    return tuple(key)


def parse_schema_devices(schema_sql: str) -> dict[str, dict]:
    devices: dict[str, dict] = {}
    for model_id, market_name, platform, position, updated_at in INSERT_ROW_RE.findall(
        schema_sql
    ):
        devices[model_id] = {
            "model_id": model_id,
            "market_name": market_name,
            "platform": platform,
            "camera_position_portrait": position,
            "updated_at": updated_at,
        }
    return devices


def chip_generation(soc: str, letter: str) -> int | None:
    match = re.match(r"{letter}(\d+)".format(letter=letter), soc or "", re.IGNORECASE)
    if match:
        return int(match.group(1))
    return None


def infer_ipad_position(name: str, device_type: str = "", soc: str = "") -> str:
    blob = " ".join(part for part in (device_type, name, soc) if part)
    if re.search(r"mini", blob, re.IGNORECASE):
        return "TOP"

    named_m = re.search(r"\bM(\d+)\b", blob, re.IGNORECASE)
    m_gen = chip_generation(soc, "M")
    if m_gen is None and named_m:
        m_gen = int(named_m.group(1))

    is_air = bool(re.search(r"\bair\b", blob, re.IGNORECASE))
    is_pro = bool(re.search(r"\bpro\b", blob, re.IGNORECASE))

    if is_air:
        return "RIGHT" if m_gen is not None and m_gen >= 2 else "TOP"
    if is_pro:
        return "RIGHT" if m_gen is not None and m_gen >= 4 else "TOP"

    generation = re.search(
        r"\((\d+)(?:st|nd|rd|th) generation\)", name, re.IGNORECASE
    )
    if generation and int(generation.group(1)) >= 10:
        return "RIGHT"

    named_a = re.search(r"iPad \(A(\d+)\)", name, re.IGNORECASE)
    a_gen = chip_generation(soc, "A")
    if named_a:
        a_gen = int(named_a.group(1))
    if a_gen is not None and a_gen >= 16:
        return "RIGHT"

    return "TOP"


def infer_ipad_position_from_family(family: str, market_name: str) -> str:
    if family in KNOWN_IPAD_FAMILY_POSITION:
        return KNOWN_IPAD_FAMILY_POSITION[family]
    return infer_ipad_position(market_name, device_type=family, soc="")


def as_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        for item in value:
            text = as_text(item)
            if text:
                return text
        return ""
    return str(value).strip()


def appledb_identifiers(device: dict) -> list[str]:
    ident = device.get("identifier") or []
    if isinstance(ident, str):
        ident = [ident]
    return [item for item in ident if isinstance(item, str)]


def parse_appledb(devices: list) -> list[dict]:
    parsed: list[dict] = []
    seen: set[str] = set()
    for device in devices:
        name = as_text(device.get("name"))
        if not name or name.lower().startswith("unreleased"):
            continue
        device_type = as_text(device.get("type"))
        soc = as_text(device.get("soc"))
        for model_id in appledb_identifiers(device):
            if not IPAD_HW_ID_RE.match(model_id) or model_id in seen:
                continue
            seen.add(model_id)
            parsed.append(
                {
                    "model_id": model_id,
                    "market_name": name,
                    "platform": "iOS",
                    "camera_position_portrait": infer_ipad_position(
                        name, device_type, soc
                    ),
                }
            )
    return parsed


def parse_devicekit(source: str) -> list[dict]:
    family_names: dict[str, str] = {}
    for market_name, family in DEVICEKIT_NAME_RE.findall(source):
        if family.startswith("iPad"):
            family_names[family] = market_name

    devices: list[dict] = []
    seen: set[str] = set()
    for identifier_blob, family in DEVICEKIT_MAP_RE.findall(source):
        market_name = family_names.get(family, family)
        position = infer_ipad_position_from_family(family, market_name)
        for model_id in IDENTIFIER_RE.findall(identifier_blob):
            if model_id in seen:
                continue
            seen.add(model_id)
            devices.append(
                {
                    "model_id": model_id,
                    "market_name": market_name,
                    "platform": "iOS",
                    "camera_position_portrait": position,
                }
            )
    return devices


def infer_samsung_position(_model_id: str, market_name: str) -> str | None:
    if SAMSUNG_LANDSCAPE_NAME_RE.search(market_name + " "):
        return "RIGHT"
    return None


def parse_androidtrackers(by_model: dict) -> list[dict]:
    devices: list[dict] = []
    seen: set[str] = set()
    for model_id, entries in by_model.items():
        if not SAMSUNG_MODEL_RE.match(model_id) or model_id in seen:
            continue
        if not isinstance(entries, list):
            entries = [entries]
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            brand = (entry.get("brand") or "").strip()
            name = (entry.get("name") or "").strip()
            if brand.lower() != "samsung" or "tab" not in name.lower():
                continue
            position = infer_samsung_position(model_id, name)
            if position is None:
                continue
            seen.add(model_id)
            devices.append(
                {
                    "model_id": model_id,
                    "market_name": name,
                    "platform": "Android",
                    "camera_position_portrait": position,
                }
            )
            break
    return devices


def parse_play_samsung_tablets(csv_text: str) -> list[dict]:
    sample = csv_text.lstrip("\ufeff")
    reader = csv.DictReader(io.StringIO(sample))
    devices: list[dict] = []
    seen: set[str] = set()

    for row in reader:
        branding = (row.get("Retail Branding") or row.get("Retail_Branding") or "").strip()
        market_name = (row.get("Marketing Name") or row.get("Marketing_Name") or "").strip()
        model_id = (row.get("Model") or "").strip()
        if branding.lower() != "samsung":
            continue
        if not SAMSUNG_MODEL_RE.match(model_id):
            continue
        if "tab" not in market_name.lower():
            continue
        position = infer_samsung_position(model_id, market_name)
        if position is None:
            continue
        if model_id in seen:
            continue
        seen.add(model_id)
        devices.append(
            {
                "model_id": model_id,
                "market_name": market_name,
                "platform": "Android",
                "camera_position_portrait": position,
            }
        )
    return devices


def merge_devices(
    existing: dict[str, dict], incoming: list[dict], now: str
) -> tuple[list[str], list[str]]:
    added: list[str] = []
    renamed: list[str] = []
    for device in incoming:
        model_id = device["model_id"]
        if model_id in existing:
            current = existing[model_id]
            new_name = device["market_name"]
            if new_name and new_name != current["market_name"]:
                current["market_name"] = new_name
                current["updated_at"] = now
                renamed.append(model_id)
            continue
        existing[model_id] = {
            "model_id": model_id,
            "market_name": device["market_name"],
            "platform": device["platform"],
            "camera_position_portrait": device["camera_position_portrait"],
            "updated_at": now,
        }
        added.append(model_id)
    return added, renamed


def render_schema(devices: dict[str, dict]) -> str:
    grouped: dict[tuple[str, str], list[dict]] = {}
    for device in devices.values():
        key = (device["platform"], device["camera_position_portrait"])
        grouped.setdefault(key, []).append(device)

    platform_order = {"iOS": 0, "Android": 1}
    position_order = {"RIGHT": 0, "TOP": 1, "LEFT": 2}

    chunks = [SCHEMA_HEADER.rstrip(), ""]
    for platform, position in sorted(
        grouped,
        key=lambda item: (platform_order.get(item[0], 9), position_order.get(item[1], 9)),
    ):
        rows = sorted(
            grouped[(platform, position)], key=lambda item: model_sort_key(item["model_id"])
        )
        label = {
            "RIGHT": "landscape-edge front camera (RIGHT in portrait)",
            "TOP": "short-edge front camera (TOP in portrait)",
            "LEFT": "long-edge front camera (LEFT in portrait)",
        }[position]
        chunks.append("-- {platform} / {position} — {label}".format(
            platform=platform, position=position, label=label
        ))
        chunks.append(
            "INSERT OR IGNORE INTO devices "
            "(model_id, market_name, platform, camera_position_portrait, updated_at) VALUES"
        )
        value_lines = []
        for device in rows:
            value_lines.append(
                "  ('{model_id}', '{market_name}', '{platform}', '{position}', '{updated_at}')".format(
                    model_id=sql_escape(device["model_id"]),
                    market_name=sql_escape(device["market_name"]),
                    platform=sql_escape(device["platform"]),
                    position=sql_escape(device["camera_position_portrait"]),
                    updated_at=sql_escape(device["updated_at"]),
                )
            )
        chunks.append(",\n".join(value_lines) + ";")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def write_schema(schema_sql: str) -> None:
    with open(SCHEMA_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(schema_sql)


def load_play_devices() -> list[dict]:
    payload = fetch_bytes(PLAY_DEVICES_URL)
    for encoding in ("utf-16", "utf-8-sig", "utf-8", "latin-1"):
        try:
            text = payload.decode(encoding)
        except UnicodeDecodeError:
            continue
        if "Marketing Name" in text or "Retail Branding" in text:
            return parse_play_samsung_tablets(text)
    raise RuntimeError("Could not decode Google Play supported-devices.csv")


def load_ios_devices() -> tuple[list[dict], str]:
    print("Fetching AppleDB…")
    try:
        catalog = fetch_json(APPLEDB_DEVICES_URL)
        ipads = parse_appledb(catalog)
        if ipads:
            print("  parsed {count} iPad identifiers".format(count=len(ipads)))
            return ipads, "AppleDB"
        print("  AppleDB returned no iPad identifiers; falling back", file=sys.stderr)
    except Exception as exc:  # noqa: BLE001
        print("  AppleDB failed ({exc}); falling back to DeviceKit".format(exc=exc), file=sys.stderr)

    print("Fetching DeviceKit…")
    ipads = parse_devicekit(fetch_text(DEVICEKIT_URL))
    print("  parsed {count} iPad identifiers".format(count=len(ipads)))
    return ipads, "DeviceKit"


def load_android_devices() -> tuple[list[dict], str]:
    print("Fetching androidtrackers certified-android-devices…")
    try:
        by_model = fetch_json(ANDROIDTRACKERS_BY_MODEL_URL)
        tablets = parse_androidtrackers(by_model)
        if tablets:
            print("  parsed {count} Galaxy Tab landscape-camera models".format(count=len(tablets)))
            return tablets, "androidtrackers"
        print("  androidtrackers returned no tablet models; falling back", file=sys.stderr)
    except Exception as exc:  # noqa: BLE001
        print(
            "  androidtrackers failed ({exc}); falling back to Google Play CSV".format(exc=exc),
            file=sys.stderr,
        )

    print("Fetching Google Play supported devices…")
    tablets = load_play_devices()
    print("  parsed {count} Galaxy Tab landscape-camera models".format(count=len(tablets)))
    return tablets, "Google Play CSV"


def sync(include_android: bool = True) -> int:
    with open(SCHEMA_PATH, "r", encoding="utf-8") as handle:
        schema_sql = handle.read()
    devices = parse_schema_devices(schema_sql)

    now = utc_now()
    ipads, ios_source = load_ios_devices()
    added_ios, renamed_ios = merge_devices(devices, ipads, now)

    added_android: list[str] = []
    renamed_android: list[str] = []
    android_source = "skipped"
    if include_android:
        try:
            tablets, android_source = load_android_devices()
            added_android, renamed_android = merge_devices(devices, tablets, now)
        except Exception as exc:  # noqa: BLE001
            print("  skipped Android sync: {exc}".format(exc=exc), file=sys.stderr)

    write_schema(render_schema(devices))

    added = added_ios + added_android
    renamed = renamed_ios + renamed_android
    print("schema.sql now has {count} devices".format(count=len(devices)))
    print("  iOS source: {source}".format(source=ios_source))
    print("  Android source: {source}".format(source=android_source))
    if added:
        preview = ", ".join(sorted(added)[:20])
        extra = "" if len(added) <= 20 else " …"
        print("  added ({count}): {preview}{extra}".format(
            count=len(added), preview=preview, extra=extra
        ))
    if renamed:
        print("  refreshed {count} market names".format(count=len(renamed)))
    if not added and not renamed:
        print("  no catalog changes")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync tablet identifiers into schema.sql")
    parser.add_argument(
        "--ios-only",
        action="store_true",
        help="Only sync iPad identifiers from AppleDB",
    )
    args = parser.parse_args()
    return sync(include_android=not args.ios_only)


if __name__ == "__main__":
    sys.exit(main())
