#!/usr/bin/env python3
"""Monthly device catalog sync.

Pulls new tablet identifiers from DeviceKit (iPad hardware strings) and the
Google Play supported-devices list (Samsung Galaxy Tab model codes), infers
front-camera placement, and merges them into schema.sql.

Existing rows keep their curated camera_position_portrait and market_name.
New rows get an inferred position; review those in the monthly PR.

Standard library only.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import io
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
SCHEMA_PATH = os.path.join(ROOT, "schema.sql")

DEVICEKIT_URL = (
    "https://raw.githubusercontent.com/devicekit/DeviceKit/"
    "master/Source/Device.generated.swift"
)
PLAY_DEVICES_URL = "https://storage.googleapis.com/play_public/supported_devices.csv"

USER_AGENT = "MobileCameraPlacementDB/1.0 (+https://github.com/amkorousagi/MobileCameraPlacementDB)"

INSERT_ROW_RE = re.compile(
    r"\(\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'"
    r"\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*\)"
)

DEVICEKIT_MAP_RE = re.compile(
    r'case\s+((?:"iPad[^"]+"\s*,\s*)*"iPad[^"]+")\s*:\s*return\s+(\w+)'
)
DEVICEKIT_NAME_RE = re.compile(
    r"Device is an \[([^\]]+)\][^\n]*\n(?:[^\n]*\n)*?\s*case (\w+)",
    re.MULTILINE,
)
IDENTIFIER_RE = re.compile(r'"(iPad[^"]+)"')

# DeviceKit enum case -> portrait camera edge. These families are confirmed.
KNOWN_IPAD_FAMILY_POSITION = {
    "iPad10": "RIGHT",
    "iPadA16": "RIGHT",
    "iPadAir11M2": "RIGHT",
    "iPadAir13M2": "RIGHT",
    "iPadAir11M3": "RIGHT",
    "iPadAir13M3": "RIGHT",
    "iPadAir11M4": "RIGHT",
    "iPadAir13M4": "RIGHT",
    "iPadPro11M4": "RIGHT",
    "iPadPro13M4": "RIGHT",
    "iPadPro11M5": "RIGHT",
    "iPadPro13M5": "RIGHT",
}

# Galaxy Tab families whose selfie camera sits on the long edge.
SAMSUNG_LANDSCAPE_NAME_RE = re.compile(
    r"galaxy tab s(?:7|8|9|1[0-9])(?:\+| ultra| fe(?:\+)?| lite)?(?:\s|$)",
    re.IGNORECASE,
)
SAMSUNG_MODEL_RE = re.compile(r"^SM-[TX][0-9]{3}[A-Z0-9]*$", re.IGNORECASE)

SCHEMA_HEADER = """\
-- Mobile Camera Placement DB
-- Language-agnostic hardware mapping of tablet front-camera location
-- in portrait orientation: RIGHT | TOP | LEFT.
--
-- iOS identifiers follow Apple's hardware strings (e.g. iPad16,3),
-- matching DeviceKit: https://github.com/devicekit/DeviceKit
-- Android identifiers follow Samsung model codes (e.g. SM-X910).
--
-- camera_position_portrait:
--   RIGHT  camera is on the long edge (right side in portrait; top in landscape)
--   TOP    camera is on the short edge (classic portrait placement)
--   LEFT   reserved for devices with the camera on the opposite long edge
--
-- updated_at is stored as a stable ISO-8601 UTC timestamp so rebuilds are
-- deterministic. Monthly sync bumps it only when a row is added or changed.
-- This file is regenerated by sync_sources.py; curated positions are preserved.

CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    model_id TEXT UNIQUE NOT NULL,
    market_name TEXT NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('iOS', 'Android')),
    camera_position_portrait TEXT NOT NULL CHECK (camera_position_portrait IN ('RIGHT', 'TOP', 'LEFT')),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )


def fetch_text(url: str, encoding: str = "utf-8") -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = response.read()
    return payload.decode(encoding)


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def model_sort_key(model_id: str) -> tuple:
    parts = re.findall(r"[A-Za-z]+|\d+", model_id)
    key = []
    for part in parts:
        key.append((1, int(part)) if part.isdigit() else (0, part.upper()))
    return tuple(key)


def parse_schema_devices(schema_sql: str) -> dict[str, dict]:
    devices: dict[str, dict] = {}
    for model_id, market_name, platform, position, updated_at in INSERT_ROW_RE.findall(
        schema_sql
    ):
        devices[model_id] = {
            "model_id": model_id,
            "market_name": market_name,
            "platform": platform,
            "camera_position_portrait": position,
            "updated_at": updated_at,
        }
    return devices


def infer_ipad_position(family: str, market_name: str) -> str:
    if family in KNOWN_IPAD_FAMILY_POSITION:
        return KNOWN_IPAD_FAMILY_POSITION[family]

    blob = "{family} {name}".format(family=family, name=market_name)

    if re.search(r"mini", blob, re.IGNORECASE):
        return "TOP"

    air_chip = re.search(r"Air.*M(\d+)", blob, re.IGNORECASE)
    if air_chip and int(air_chip.group(1)) >= 2:
        return "RIGHT"

    pro_chip = re.search(r"Pro.*M(\d+)", blob, re.IGNORECASE)
    if pro_chip and int(pro_chip.group(1)) >= 4:
        return "RIGHT"

    numbered = re.match(r"iPad(\d+)$", family)
    if numbered and int(numbered.group(1)) >= 10:
        return "RIGHT"

    if re.match(r"iPadA\d+", family):
        return "RIGHT"

    generation = re.search(
        r"iPad \((\d+)(?:st|nd|rd|th) generation\)", market_name, re.IGNORECASE
    )
    if generation and int(generation.group(1)) >= 10:
        return "RIGHT"

    return "TOP"


def parse_devicekit(source: str) -> list[dict]:
    family_names: dict[str, str] = {}
    for market_name, family in DEVICEKIT_NAME_RE.findall(source):
        if family.startswith("iPad"):
            family_names[family] = market_name

    devices: list[dict] = []
    seen: set[str] = set()
    for identifier_blob, family in DEVICEKIT_MAP_RE.findall(source):
        market_name = family_names.get(family, family)
        position = infer_ipad_position(family, market_name)
        for model_id in IDENTIFIER_RE.findall(identifier_blob):
            if model_id in seen:
                continue
            seen.add(model_id)
            devices.append(
                {
                    "model_id": model_id,
                    "market_name": market_name,
                    "platform": "iOS",
                    "camera_position_portrait": position,
                }
            )
    return devices


def infer_samsung_position(_model_id: str, market_name: str) -> str | None:
    if SAMSUNG_LANDSCAPE_NAME_RE.search(market_name + " "):
        return "RIGHT"
    return None


def parse_play_samsung_tablets(csv_text: str) -> list[dict]:
    # Google's export is historically UTF-16; fall back if decoded as UTF-8.
    sample = csv_text.lstrip("\ufeff")
    reader = csv.DictReader(io.StringIO(sample))
    devices: list[dict] = []
    seen: set[str] = set()

    for row in reader:
        branding = (row.get("Retail Branding") or row.get("Retail_Branding") or "").strip()
        market_name = (row.get("Marketing Name") or row.get("Marketing_Name") or "").strip()
        model_id = (row.get("Model") or "").strip()
        if branding.lower() != "samsung":
            continue
        if not SAMSUNG_MODEL_RE.match(model_id):
            continue
        if "tab" not in market_name.lower():
            continue
        position = infer_samsung_position(model_id, market_name)
        if position is None:
            continue
        if model_id in seen:
            continue
        seen.add(model_id)
        devices.append(
            {
                "model_id": model_id,
                "market_name": market_name,
                "platform": "Android",
                "camera_position_portrait": position,
            }
        )
    return devices


def merge_devices(existing: dict[str, dict], incoming: list[dict], now: str) -> tuple[dict[str, dict], list[str]]:
    added: list[str] = []
    for device in incoming:
        model_id = device["model_id"]
        if model_id in existing:
            current = existing[model_id]
            changed = False
            # Fill in a better market name if the stored one is just the identifier.
            if current["market_name"] == model_id and device["market_name"] != model_id:
                current["market_name"] = device["market_name"]
                changed = True
            if changed:
                current["updated_at"] = now
            continue
        existing[model_id] = {
            "model_id": model_id,
            "market_name": device["market_name"],
            "platform": device["platform"],
            "camera_position_portrait": device["camera_position_portrait"],
            "updated_at": now,
        }
        added.append(model_id)
    return existing, added


def render_schema(devices: dict[str, dict]) -> str:
    grouped: dict[tuple[str, str], list[dict]] = {}
    for device in devices.values():
        key = (device["platform"], device["camera_position_portrait"])
        grouped.setdefault(key, []).append(device)

    platform_order = {"iOS": 0, "Android": 1}
    position_order = {"RIGHT": 0, "TOP": 1, "LEFT": 2}

    chunks = [SCHEMA_HEADER.rstrip(), ""]
    for platform, position in sorted(
        grouped,
        key=lambda item: (platform_order.get(item[0], 9), position_order.get(item[1], 9)),
    ):
        rows = sorted(grouped[(platform, position)], key=lambda item: model_sort_key(item["model_id"]))
        label = {
            "RIGHT": "landscape-edge front camera (RIGHT in portrait)",
            "TOP": "short-edge front camera (TOP in portrait)",
            "LEFT": "long-edge front camera (LEFT in portrait)",
        }[position]
        chunks.append("-- {platform} / {position} — {label}".format(
            platform=platform, position=position, label=label
        ))
        chunks.append(
            "INSERT OR IGNORE INTO devices "
            "(model_id, market_name, platform, camera_position_portrait, updated_at) VALUES"
        )
        value_lines = []
        for device in rows:
            value_lines.append(
                "  ('{model_id}', '{market_name}', '{platform}', '{position}', '{updated_at}')".format(
                    model_id=sql_escape(device["model_id"]),
                    market_name=sql_escape(device["market_name"]),
                    platform=sql_escape(device["platform"]),
                    position=sql_escape(device["camera_position_portrait"]),
                    updated_at=sql_escape(device["updated_at"]),
                )
            )
        chunks.append(",\n".join(value_lines) + ";")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def write_schema(schema_sql: str) -> None:
    with open(SCHEMA_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(schema_sql)


def load_play_devices() -> list[dict]:
    raw = urllib.request.Request(PLAY_DEVICES_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(raw, timeout=60) as response:
        payload = response.read()
    for encoding in ("utf-16", "utf-8-sig", "utf-8", "latin-1"):
        try:
            text = payload.decode(encoding)
        except UnicodeDecodeError:
            continue
        if "Marketing Name" in text or "Retail Branding" in text:
            return parse_play_samsung_tablets(text)
    raise RuntimeError("Could not decode Google Play supported-devices.csv")


def sync(include_android: bool = True) -> int:
    with open(SCHEMA_PATH, "r", encoding="utf-8") as handle:
        schema_sql = handle.read()
    devices = parse_schema_devices(schema_sql)
    before = set(devices)

    print("Fetching DeviceKit…")
    devicekit_source = fetch_text(DEVICEKIT_URL)
    ipads = parse_devicekit(devicekit_source)
    print("  parsed {count} iPad identifiers".format(count=len(ipads)))

    now = utc_now()
    devices, added_ios = merge_devices(devices, ipads, now)

    added_android: list[str] = []
    if include_android:
        print("Fetching Google Play supported devices…")
        try:
            samsung = load_play_devices()
            print("  parsed {count} Galaxy Tab landscape-camera models".format(count=len(samsung)))
            devices, added_android = merge_devices(devices, samsung, now)
        except Exception as exc:  # noqa: BLE001 — keep monthly job resilient
            print("  skipped Android sync: {exc}".format(exc=exc), file=sys.stderr)

    added = [model_id for model_id in devices if model_id not in before]
    write_schema(render_schema(devices))

    print("schema.sql now has {count} devices".format(count=len(devices)))
    if added:
        preview = ", ".join(sorted(added)[:20])
        extra = "" if len(added) <= 20 else " …"
        print("  added ({count}): {preview}{extra}".format(
            count=len(added), preview=preview, extra=extra
        ))
    else:
        print("  no new identifiers")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync tablet identifiers into schema.sql")
    parser.add_argument(
        "--ios-only",
        action="store_true",
        help="Only sync iPad identifiers from DeviceKit",
    )
    args = parser.parse_args()
    return sync(include_android=not args.ios_only)


if __name__ == "__main__":
    sys.exit(main())
